---
name: CI

env:
  PHP_VERSION: 8.0

on:
  pull_request:
    branches: [main]

jobs:
  build_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: shivammathur/setup-php@fefbd7a497af49675efddfb3d1b068acb4044a8a
        with:
          php-version: ${{ env.PHP_VERSION }}

      - run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
  
      - run: composer test